name: Generate Resume PDF

on:
  push:
    branches: [ main, master ]
    paths:
      - 'README.md'
      - 'style.css'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Pull Docker image
      run: docker pull ghcr.io/${{ github.repository_owner }}/resume-generator:latest || echo "Image not found, might need to run Docker build workflow first"
    
    - name: Generate Resume PDF
      run: |
        mkdir -p ./output
        chmod 777 ./output
        
        docker run --rm \
          -v $(pwd):/resume \
          -v $(pwd)/output:/output \
          ghcr.io/${{ github.repository_owner }}/resume-generator:latest \
          README.md \
          /output/david-aizenberg-resume.pdf \
          style.css
        
        # Check the output
        ls -la ./output
    
    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: resume-${{ steps.date.outputs.DATE }}
        name: Resume Update ${{ steps.date.outputs.DATE }}
        body: |
          Automatically generated resume PDF
          Last updated: ${{ steps.date.outputs.DATE }}
        files: ./output/david-aizenberg-resume.pdf
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
